### ISSUE TITLE
Roadmap for clrs2sol-pl migration

### ISSUE THREAD

**Issue by wojtask** [wojtask/clrs4e-solutions#1]
clrs2sol-pl project, previously called [CormenSol](https://github.com/wojtask/CormenSol) is going to be frozen indefinitely on 4/30. It contains (almost) all solutions for chapters 1-18 and appendices A-C from CLRS 2nd edition. The solutions are in Polish and treat the Polish edition of the book as a base. Assume that once the project has been frozen, the solutions are all at the GREEN level of acceptance.

This story is to prepare a roadmap with milestones and timelines for producing roughly the same amount of content in the current project as in clrs2sol-pl. This involves:

- [x] setting up the document stub,
- [x] creating the set of rules based on [clrs2sol-pl RULES](https://github.com/wojtask/CormenSol/blob/master/RULES),
- [x] creating README based on [clrs2sol-pl README.md](https://github.com/wojtask/CormenSol/blob/master/README.md),
- [x] moving any outstanding issues from clrs2sol-pl,
- [x] creating milestones for migrating the solutions from the legacy project.

For exercises missing in or changed substantially from the 2nd edition, preferrably fill in the gaps by relevant solutions. It is to decide later if bigger chunks that were missing before should be added right away along with migrating the older solutions, or left until the migration is done.

**Comment by wojtask** [comment]
Freeze deadline for CormenSol has been pushed forward to the end of 2022.
